{{- range .Values.kingdoms }}
{{- $kingdom := .name }}
{{- range .towns }}
{{- $town := .name }}
{{- range .shops }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .type }}
  namespace: {{ $kingdom }}
  labels:
    town: {{ $town }}
    shop: {{ .type }}
spec:
  selector:
    town: {{ $town }}
    shop: {{ .type }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
{{- end }}
{{- end }}
{{- end }}
