{{- range .Values.kingdoms }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: civ-worker
  namespace: {{ .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-patcher
  namespace: {{ .name }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patcher-binding
  namespace: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-patcher
subjects:
  - kind: ServiceAccount
    name: civ-worker
    namespace: {{ .name }}
{{- end }}
